Refatoração do template de geração de testes
deveagletec/alfred pull request #19
Opened 2019-07-05 18:25 UTC by warleyxavier

Atualizado template de geração de testes de modo a gerar o mock de consulta de forma menos duplicada e valide informações consistentes

2019-07-17 18:33 UTC, msnts requested changes

2019-07-17 18:33 UTC, msnts commented on resources/templates/default/TViewModelTest.pas
> +	  LancouExcecao := E.ContainsMsgLike(PropertyName, Msg);
Use a instrução:
Assert.AreEqual(IsValid, E.ContainsMsgLike(PropertyName, Msg));

2019-07-18 20:54 UTC, warleyxavier commented on resources/templates/default/TViewModelTest.pas
> +	  LancouExcecao := E.ContainsMsgLike(PropertyName, Msg);
Adicionado trecho sugerido. Fez-se necessário ainda manter o Assert fora da zona do Except para possibilitar a validação de dados válidos.

2019-07-19 11:05 UTC, msnts approved these changes

2019-07-19 11:05 UTC, merged