AF 20 - Implementação de exibição de helper para usuários
deveagletec/alfred pull request #21
Opened 2019-07-08 11:56 UTC by warleyxavier

Alterações realizadas:
* Implementada classe que exibirá helpers para auxiliar o uso, a mesma utiliza dados inseridos nos anotations dos comandos
* Extraídos records da classe de registros dos comandos e adicionados a uma unit própria
* Implementado método NewEmptyLine na classe de console

2019-07-10 11:13 UTC, msnts requested changes

2019-07-10 11:13 UTC, msnts commented on src/core/Eagle.Alfred.Core.CommandRegister.pas
> +
Remover linhas em branco desnecessárias

2019-07-10 11:13 UTC, msnts commented on src/core/Eagle.Alfred.Core.CommandRegister.pas
> +  FCommands := TDictionary < string, TDictionary < string, TCommandMetaData >>.Create;
Remover espaços desnecessários

2019-07-10 11:13 UTC, msnts commented on src/core/Eagle.Alfred.Core.CommandRegister.pas
> +  if not FCommands.Items[GroupName].ContainsKey(CommandName) then
If desnecessário. Faça a atribuição diretamente no Result

Result := FCommands.Items[GroupName].ContainsKey(CommandName);

2019-07-10 11:13 UTC, msnts commented on src/Eagle.Alfred.pas
> +
Remover linhas em branco desnecessárias

2019-07-10 11:13 UTC, msnts commented on packages/Alfred.dpr
> +  Eagle.Alfred.Core.CommandRegisterData in '..\src\core\Eagle.Alfred.Core.CommandRegisterData.pas';
Arquivo não existente na pasta

2019-07-15 11:15 UTC, warleyxavier commented
Alterações aplicadas

2019-07-15 11:58 UTC, msnts approved these changes

2019-07-15 11:58 UTC, merged