Implementação de novos comandos e opções
deveagletec/alfred pull request #24
Opened 2019-07-22 20:44 UTC by warleyxavier

**Realizadas as seguintes alterações:**

* Implementado comando que possibilita a abertura para  edição do arquivo package, também foi incrementado um filtro de modo a possibilitar que visualize uma propriedade especifica
* Implementada opção que força a geração do script de atualização(com base em migrates) mesmo que não haja migrates com a versão current
* Implementada configuração para informar a pasta de geração do script de atualização
* Corrigida inconsistência ao scapar string json que converterá para objeto

2019-07-24 11:30 UTC, msnts requested changes

2019-07-24 11:30 UTC, msnts commented on src/command/db/update/Eagle.Alfred.Command.DB.Update.Join.pas
> +    [Option('forcegeneration', 'f', 'Force generation of script update even without migrates founded')]
O termo "forcegeneration" é muito longo. Poderia ser "force"

2019-07-24 11:30 UTC, msnts commented on src/command/db/update/Eagle.Alfred.Command.DB.Update.Join.pas
> +    [Option('savepathinfile', 's', 'Save path in file on current diretory')]
O mesmo ocorre como o termo "savepathinfile"

2019-07-26 00:07 UTC, warleyxavier commented on src/command/db/update/Eagle.Alfred.Command.DB.Update.Join.pas
> +    [Option('forcegeneration', 'f', 'Force generation of script update even without migrates founded')]
Termo alterado

2019-07-26 00:07 UTC, warleyxavier commented on src/command/db/update/Eagle.Alfred.Command.DB.Update.Join.pas
> +    [Option('savepathinfile', 's', 'Save path in file on current diretory')]
Termo alterado

2019-08-02 11:59 UTC, merged